### ISSUE TITLE
✨ [FEAT] 나눔 게시판, 채팅방 기능 구현

### ISSUE THREAD

**Issue by yujindonut** [DDWU-Re-Market/REMARKET#3]
## 👛 작업 브랜치
- feature/share-entity

## 📝 To-do
- [x] Entity 생성
- [x] 나눔 화면 생성
- [x] 쪽지 entity
- [x] 이미지 구현업로드

**Comment by eojin0814** [comment]
헤헤 오늘도 파이팅><💗
